text = input('Digite algo: ')
tipo = (type(text))
num = (text.isnumeric())
alf = (text.isalpha())
alfn = (text.isalnum())
esp = (text.isspace())

print('O tipo primitivo desse valor é: ', tipo)
print('Só tem espaços? ', esp)
print('É um número? ', num)
print('É alfabético? ', alf)
print('É alfanumérico? ', alfn)
print('Está em Maiúsculas? ', text.isupper())
print('Está em minúsculas? ', text.islower())
print('Esta capitalizada? ex:Python ', text.istitle())